---
driver:
  provision: true
  name: vagrant
  #require_chef_omnibus: 12.19.36 #13.12.3
  vagrantfiles:
    - kitchen_vagrant.rb
  customize:
    memory: 512
    cpus: 1

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      require_chef_omnibus: '12.19.36'
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[ntpdate]

  - name: custom
    run_list:
    - recipe[ntpdate]
    attributes:
      ntpdate:
        enable: true
        ntp_servers:
        - 0.de.pool.ntp.org
        - 1.de.pool.ntp.org
        - 2.de.pool.ntp.org
        - 3.de.pool.ntp.org
        crontab:
          comment: 'This cron syncs the time on Sundays mornings.'
          minute: 0
          hour: 6
          weekday: sun

  - name: disabled
    run_list:
    - recipe[ntpdate]
    attributes:
      ntpdate:
        enable: false
        ntp_servers:
        - server 0.de.pool.ntp.org
        - server 1.de.pool.ntp.org
        - server 2.de.pool.ntp.org
        - server 3.de.pool.ntp.org
        crontab:
          comment: 'This should never appear.'
          minute: 0
          hour: 6
          day: 7
