---
name: 'Test Report'
"on":
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v3
        with:
          artifact: kitchen-results
          name: Kitchen Tests
          path: '*chef*ubuntu*.xml'
          reporter: jest-junit
