---
name: 'Test Report'
"on":
  workflow_run:
    workflows:
      - ci
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: cookstyle-results
          name: Cookstyle Tests
          path: 'cookstyle.xml'
          reporter: jest-junit
      - uses: dorny/test-reporter@v1
        with:
          artifact: kitchen-results
          name: Kitchen Tests
          path: '*chef*ubuntu*.xml'
          reporter: jest-junit
